(extfs_find_entry_int): fix build due to C23 `strchr` prototype change
```
extfs.c: In function 'extfs_find_entry_int':
extfs.c:254:11: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  254 |         q = strchr (p, PATH_SEP);
      |           ^
```

Signed-off-by: Yury V. Zaytsev <yury@shurup.com>